#!/usr/bin/env python3
"""Collapse the [PROPOSED] backlog in daily logs into one reviewable queue.

Marvin proposes memory updates as `[PROPOSED …]` blocks in
`_system/memory/daily/{date}.md`; a human promotes approved items into
`_system/memory/MEMORY.md`. The proposing side has run for months and the
promoting side has not — the last promotion was 2026-05-23 against a backlog
spanning dozens of daily files — so the belief set is frozen while proposals
accumulate. Reading them in place means opening every daily file, which is why
it has not happened.

This writes a single file grouped by lens (MUNGER / PABRAI / STAHL / MOI /
COMPANY / …), newest first, with an `- [ ]` marker per item, so promotion is one
pass with checkboxes rather than dozens of file reads.

It does **not** promote anything. `_system/memory/MEMORY.md` says explicitly that
only a human promotes, and a belief entering the set unreviewed is exactly the
failure the [PROPOSED] convention exists to prevent.

Usage:
  python _system/scripts/build_memory_triage.py
  python _system/scripts/build_memory_triage.py --since 2026-07-01
  python _system/scripts/build_memory_triage.py --out _system/reviews/pending/memory_triage.md
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parents[2]
DAILY = ROOT / "_system" / "memory" / "daily"
DEFAULT_OUT = ROOT / "_system" / "reviews" / "pending" / "memory_triage.md"

HEADING = re.compile(r"^#{2,4}\s*\[PROPOSED([^\]]*)\]\s*(.*)$")
# Daily logs tag proposals two ways: a heading, or an inline bullet. A bullet
# carries its own lens and is frequently nested under a differently-tagged
# heading, so attributing it to the enclosing heading files company facts under
# MEMORY and makes the queue impossible to review lens by lens.
BULLET = re.compile(r"^[-*]\s*\[PROPOSED([^\]]*)\]\s*(.*)$")
ANY_HEADING = re.compile(r"^#{1,6}\s")
DATED = re.compile(r"(\d{4}-\d{2}-\d{2})")


def parse_file(path: Path) -> list[dict]:
    """Every [PROPOSED …] block with the bullet lines that follow it."""
    day = DATED.search(path.name)
    items: list[dict] = []
    current: dict | None = None
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.rstrip()
        match = HEADING.match(line.strip())
        if match:
            if current and current["body"]:
                items.append(current)
            current = {
                "lens": (match.group(1) or "").strip() or "GENERIC",
                "title": match.group(2).strip(),
                "day": day.group(1) if day else path.stem,
                "file": path.name,
                "body": [],
            }
            continue
        # An inline bullet is its own proposal, with its own lens, whether or not
        # it sits inside a heading block.
        bullet = BULLET.match(line.strip())
        if bullet and bullet.group(2).strip():
            items.append({
                "lens": (bullet.group(1) or "").strip() or "GENERIC",
                "title": "",
                "day": day.group(1) if day else path.stem,
                "file": path.name,
                "body": [bullet.group(2).strip()],
            })
            continue
        if current is None:
            continue
        # A non-PROPOSED heading closes the block.
        if ANY_HEADING.match(line):
            if current["body"]:
                items.append(current)
            current = None
            continue
        if line.strip():
            current["body"].append(line.strip())
    if current and current["body"]:
        items.append(current)
    return items


def dedupe(items: list[dict]) -> tuple[list[dict], int]:
    """Collapse items whose body text repeats, keeping the earliest sighting.

    The same belief is often re-proposed on successive days; promoting a
    duplicate wastes the reviewer's attention and inflates the backlog.
    """
    seen: dict[tuple, dict] = {}
    dropped = 0
    for item in items:
        key = (item["lens"], " ".join(item["body"]).lower()[:400])
        if key in seen:
            seen[key]["also_seen"].append(item["day"])
            dropped += 1
            continue
        seen[key] = {**item, "also_seen": []}
    return list(seen.values()), dropped


def render(items: list[dict], dropped: int, since: str | None) -> str:
    by_lens: dict[str, list[dict]] = defaultdict(list)
    for item in items:
        by_lens[item["lens"]].append(item)

    out: list[str] = [
        "# Memory promotion queue",
        "",
        f"Generated by `build_memory_triage.py` on {date.today().isoformat()}"
        + (f", covering daily logs from {since}." if since else "."),
        "",
        f"**{len(items)} distinct proposals** across {len(by_lens)} lens(es); "
        f"{dropped} duplicate sighting(s) collapsed.",
        "",
        "Tick an item to promote it into `_system/memory/MEMORY.md` under the matching",
        "lens, then delete the row here. Leave rejected items unticked with a one-line",
        "reason so the same proposal is not re-reviewed next month.",
        "",
        "Nothing in this file has been promoted. Only a human promotes — see the rule",
        "at the top of `MEMORY.md`.",
        "",
    ]
    for lens in sorted(by_lens, key=lambda k: (-len(by_lens[k]), k)):
        rows = sorted(by_lens[lens], key=lambda r: r["day"], reverse=True)
        out.append(f"## {lens} ({len(rows)})")
        out.append("")
        for row in rows:
            head = f"- [ ] **{row['day']}**"
            if row["title"]:
                head += f" — {row['title']}"
            out.append(head)
            for line in row["body"][:6]:
                out.append(f"      {line}")
            if row["also_seen"]:
                extra = ", ".join(sorted(set(row["also_seen"]))[:5])
                out.append(f"      *(also proposed {len(row['also_seen'])}× — {extra})*")
            out.append(f"      `{row['file']}`")
            out.append("")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--since", help="only daily logs on/after this YYYY-MM-DD")
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args(argv)

    if not DAILY.is_dir():
        print(f"no daily log directory at {DAILY}")
        return 1
    items: list[dict] = []
    for path in sorted(DAILY.glob("*.md")):
        day = DATED.search(path.name)
        if args.since and day and day.group(1) < args.since:
            continue
        items.extend(parse_file(path))

    if not items:
        print("no [PROPOSED] blocks found")
        return 0
    items, dropped = dedupe(items)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(items, dropped, args.since), encoding="utf-8")

    print(f"[ok] {out_path.relative_to(ROOT)}")
    print(f"  {len(items)} distinct proposals, {dropped} duplicate sighting(s) collapsed")
    lenses = defaultdict(int)
    for item in items:
        lenses[item["lens"]] += 1
    for lens, count in sorted(lenses.items(), key=lambda kv: -kv[1]):
        print(f"    {lens:14} {count}")
    print("\n  Nothing promoted — MEMORY.md is human-promote-only.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
